version: "3.9"

services:
  backend:
    image: tech-sup-backend
    container_name: tech-sup-backend
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "5000:5000"
    networks:
      - tech-sup-net
    restart: unless-stopped

  frontend:
    image: tech-sup-frontend
    container_name: tech-sup-frontend
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "5001:5001"
    networks:
      - tech-sup-net
    depends_on:
      - backend
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - tech-sup-net
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200",
        ]
      interval: 10s
      timeout: 10s
      retries: 30
    mem_limit: 2g
    mem_reservation: 1g

  logstash:
    image: logstash-oracle
    container_name: logstash
    build:
      context: .
      dockerfile: Dockerfile-logstash
    user: root
    environment:
      - ORACLE_DB_HOST=${ORACLE_DB_HOST}
      - ORACLE_DB_PORT=${ORACLE_DB_PORT}
      - ORACLE_DB_SID=${ORACLE_DB_SID}
      - ORACLE_DB_USER=${ORACLE_DB_USER}
      - ORACLE_DB_PASSWORD=${ORACLE_DB_PASSWORD}
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./elasticsearch/init-es.sh:/usr/share/elasticsearch/init-es.sh
    command: /bin/bash -c "chmod +x /usr/share/elasticsearch/init-es.sh && /usr/share/elasticsearch/init-es.sh && /usr/local/bin/docker-entrypoint"
    networks:
      - tech-sup-net
    depends_on:
      - elasticsearch
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9600",
        ]
      interval: 10s
      timeout: 10s
      retries: 10

volumes:
  esdata:
    driver: local

networks:
  tech-sup-net:
    driver: bridge
